name: Terraform Validator
on: [pull_request]

jobs:
  on-pull-request:
    name: On Pull Request
    runs-on: ubuntu-latest
    steps:
    
    - name: checkout
      uses: actions/checkout@master

    - name: Terraform - Init
      uses: hashicorp/terraform-github-actions/init@v0.3.5
      env:
        TF_ACTION_WORKING_DIR: "."

    - name: Terraform - Validate
      uses: hashicorp/terraform-github-actions/validate@v0.3.5
      env:
        TF_ACTION_WORKING_DIR: "."
      with:
        args: .

    - name: Terraform - Plan
      uses: hashicorp/terraform-github-actions/plan@v0.3.5
      env:
        TF_ACTION_WORKING_DIR: "."
